### ISSUE TITLE
stacktrace when returning to dashboard - instability?

### ISSUE THREAD

**Issue by robrwg** [slateci/slate-portal#46]
<img width="1057" alt="screenshot_1104" src="https://user-images.githubusercontent.com/2236996/57933527-26e37300-7883-11e9-9d5b-6999284991a1.png">

**Comment by jarofmy** [comment]
This has been a pretty tough error to debug, as it seems to only happen randomly. I've been testing around on my local machine this past week, and currently, my best guess is that there is a slight delay between the applications get request query, and unwrapping the applications' json values. I've switched the ordering, such that unwrapping the applications' json happens at a later time, and to my knowledge, have not run into this error since. I've just pushed the update and will continue testing to see if this error arises again.

**Comment by jarofmy** [comment]
Pinpointed error. Changed python 'ast.literal_eval' to 'json.loads', which is more secure and faster in comparison.
